services:
  technitium:
    image: technitium/dns-server:latest
    container_name: technitium
    hostname: technitium
    restart: unless-stopped

    ports:
      - "5380:5380/tcp"
      - "53:53/udp"
      - "53:53/tcp"

    environment:
      - TZ=Europe/Madrid

    volumes:
      - /opt/data/technitium:/etc/dns

    networks:
      - proxy_net
      - monitoring_net

networks:
  proxy_net:
    external: true

  monitoring_net:
    external: true
