services:
  nextcloud-db:
    image: mariadb:11
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW

    environment:
      - MYSQL_ROOT_PASSWORD=Template.47
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=Template.47

    volumes:
      - /opt/data/nextcloud/db:/var/lib/mysql

    networks:
      - backend_net

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped

    depends_on:
      - nextcloud-db

    ports:
      - "8081:80"

    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=Template.47

    volumes:
      - /opt/data/nextcloud/html:/var/www/html

    networks:
      - proxy_net
      - backend_net

networks:
  proxy_net:
    external: true

  backend_net:
    external: true
